### ISSUE TITLE
Tolerations are not passed from the StatefulSet to pods when adding storage definition

### ISSUE THREAD

**Issue by rotemjac** [freshworks/redis-operator#11]
### Expected behaviour

I want to use tolerations AND storage class settings.

### Actual behaviour
Tolerations are not passed from the StatefulSet to the pods when adding storage definition.

This is working:

```
  redis:
    replicas: {{ .Values.Redis.Replicas }}
    tolerations:
      - key: "node/{{ .Values.Redis.Node.TaintKey }}"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node/{{ .Values.Redis.Node.TaintKey }}"
        operator: "Exists"
        effect: "NoExecute"
```

This is not:
```
  redis:
    storage:
      persistentVolumeClaim:
        metadata:
          name: redisfailover-persistent
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 0.2Gi
          storageClassName: st1
    replicas: {{ .Values.Redis.Replicas }}
    tolerations:
      - key: "node/{{ .Values.Redis.Node.TaintKey }}"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node/{{ .Values.Redis.Node.TaintKey }}"
        operator: "Exists"
        effect: "NoExecute"
```

### Steps to reproduce the behaviour

Combine Storage definition with Tolerations - like I showed above.

### Environment

How are the pieces configured?
* Redis Operator version: 3.2.9
* Kubernetes version: 1.31
